---
  - name: ip address of backend server
    hosts: backend
    tasks:
      - name: get ip address
        ipify_facts:
        register: public_ip
  
  - name: Configurations on frontend servers
    hosts: frontend
    remote_user: cloud-user
    become: true
    roles:
      - nginx

  - name: Configurations on backend servers
    hosts: backend
    remote_user: ubuntu
    become: true
    roles:
      - netdata
